### ISSUE TITLE
results.csv just one line

### ISSUE THREAD

**Issue by THSWind** [ThibautTheate/Unconstrained-Monotonic-Deep-Q-Network-algorithm#1]
hello, buddy.
I have deployed your project, then one problem occurs. When I run it, I found it created two result.csv (in "experiments/UMDQN_KL_xxxx/ ") ,but only 1 line in it. I don't know what's wrong. could u help me?
command line is:
python main.py -algorithm UMDQN_KL -environment Acrobot-v1

or:
python main.py -algorithm 'UMDQN_KL' -environment 'MinAtar/Breakout-v0' -episode '1000000'

it doesn't work, or just 1 line in result.csv.

waiting for you reply, thank you very much~

**Comment by ThibautTheate** [comment]
Hello THSWind,

I have just run the code without being able to reproduce your problem.

But I have two suggestions for you:
1.	Set the flag “verbose” to “True” on line 93 of the main.py file.
2.	Check the proper installation of all the dependencies.
Also be aware that some simulations are quite long to run, especially without GPU hardware acceleration.

If these suggestions do not solve your problem, could you please be more specific regarding the single line appearing in the results files?

I hope this will help you.

Thibaut Théate

**Comment by THSWind** [comment]
Thank you so much, ThibautTheate,

Your project looks great, it may help me a lot. 
I do it like you have mentioned(Set verbose=True). In the meantime, I met a problem that "KeyError: 'render_modes' KeyError::command not found". When I change the version of gym from 0.25.1 to 0.24.1.  it works. 

 Another question occur, When I run  environment "FreewayNoFrameskip-v4", it display  "gym.error.NameNotFound: Environment FreewayNoFrameskip doesn't exist".

 I wander if it is the version of gym not match your settings.  
1. would mind to run a command that "pip freeze > requirements.txt", and show me ? please
2. beacuse the problem of "environment doesn't exist" above, I want to know, if I want to make it support another environment (eg: Swimmer-v4, or others), how to achieve it?

All the best!

**Comment by ThibautTheate** [comment]
I may be wrong, but it seems you are missing some dependencies since the Atari games are not included in your gym library.

Could you run the following command and try again?
pip install gym[atari]

Keep me informed of your results, I hope this helps.

**Comment by THSWind** [comment]
I run it and try it again, then:

(py3.7.7) root@qedrpg:/mnt/work3/rate1/Unconstrained-Monotonic-Deep-Q-Network-algorithm# python main.py -algorithm UMDQN_C -environment FreewayNoFrameskip-v4
A.L.E: Arcade Learning Environment (version 0.7.5+db37282)
[Powered by Stella]
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    env = atariWrapper.wrapper(environment, stickyActionsProba=0.25)
  File "/mnt/work3/rate1/Unconstrained-Monotonic-Deep-Q-Network-algorithm/AtariWrapper.py", line 656, in wrapper
    env = gym.make(environment)
  File "/root/miniconda3/envs/py3.7.7/lib/python3.7/site-packages/gym/envs/registration.py", line 592, in make
    env = env_creator(**_kwargs)
  File "/root/miniconda3/envs/py3.7.7/lib/python3.7/site-packages/gym/envs/atari/environment.py", line 136, in __init__
    self.seed()
  File "/root/miniconda3/envs/py3.7.7/lib/python3.7/site-packages/gym/envs/atari/environment.py", line 188, in seed
    f'We\'re Unable to find the game "{self._game}". Note: Gym no longer distributes ROMs. '
gym.error.Error: We're Unable to find the game "Freeway". Note: Gym no longer distributes ROMs. If you own a license to use the necessary ROMs for research purposes you can download them via `pip install gym[accept-rom-license]`. Otherwise, you should try importing "Freeway" via the command `ale-import-roms`. If you believe this is a mistake perhaps your copy of "Freeway" is unsupported. To check if this is the case try providing the environment variable `PYTHONWARNINGS=default::ImportWarning:ale_py.roms`. For more information see: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management

**Comment by THSWind** [comment]
Hello, @ThibautTheate ,

Could you please tell me how to get td-error in your code? I located it in UMDQN_C.py-> def leanring. But I don't know how to get td-error?

Waiting for you reply~

**Comment by THSWind** [comment]
Thank you very much, ThibautTheate.  it works.
